[display]
x = 2400
y = 200
font_size = 16

# värit hex-arvoina
text_color = "#FFFFFF" # valkoinen "#FFFFFF"
bg_color = "#000000" # musta "#000000"

alpha_channel = 0.5 # 0-1 läpinäkyvyys

# Ei kannata muuttaa
background = true # true/false Jos false, niin kirjainten välistä voi klikkailla


[durations_minutes]
day = 50    # Rusty moose eu bi: 50
night = 10  # Rusty moose eu bi: 10
